# Generated by Django 5.2.8 on 2025-11-24 14:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_prodcutrating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProdcutRating',
            new_name='ProductRating',
        ),
    ]
